---
title: "Exploitation de l'EGT 2010"
author: "Cantien Collinet"
date: "`r format(Sys.time(), '%A %d %B %Y')`"
output:
  pdf_document: default
  html_notebook: default
---

# Préparation du traitement
Installation des librairies et importation des données
```{r, setup, results='hide', message=FALSE}
library(tidyverse)
library(haven)
library(viridis)
library(questionr)

# Viridis colors as default for ggplot2 : easier to read by those with colorblindness, and print well in grey scale.
options(ggplot2.continuous.colour="viridis")
options(ggplot2.continuous.fill = "viridis")
scale_colour_discrete <- scale_colour_viridis_d
scale_fill_discrete <- scale_fill_viridis_d

menages <- read_sas("../data/men2010.sas7bdat")
individus <- read_sas("../data/ind2010.sas7bdat")
deplacements <- read_sas("../data/dplct2010.sas7bdat")
trajets <- read_sas("../data/trajet2010.sas7bdat")

# Recode to factors, except a few columns
menages <- menages %>%
  mutate_at(vars(-POIDSM, -MNP, -MNP5, -MNPMOB, -MNPACT, -LOY_HC, -CHG, -LOY_PARK, -NBPI, -SURF, -ANEM, -MNEM, -NB_VELO, -NB_VAE, -NB_2RM, -NB_VEH, -ANKMRM1, -ANKMV1, -CPTKMV1, -ANKMV2, -CPTKMV2, -ANKMV3, -CPTKMV3, -ANKMV4, -CPTKMV4), factor)
individus <- individus %>%
  mutate_at(vars(-POIDSP, -AGE, -NBDEPL, -NBDEPLVP, -NBDEPLVPC, -NBDEPLTC, -NBDEPLVELO, -NBDEPL2RM, -NBDEPLMAP, -DDOMTRAV), factor)
deplacements <- deplacements %>%
  mutate_at(vars(-POIDSP, -DPORTEE, -DUREE, -NBTRAJ, -NBTRAJVP, -NBTRAJVPC, -NBTRAJTC, -NBTRAJVELO, -NBTRAJ2RM, -NBCO), factor)
trajets <- trajets %>%
  mutate_at(vars(-POIDSP, -TPORTEE), factor)
```

<!--
# Exploration du jeu de données

```{r, child=c('exploration.Rmd')}
```
-->

# Qui sont les membres de la PCS 56 ?

## Lien à la personne de référence
```{r}
ALL_LIENPREF <- individus %>%
  mutate(LIENPREF = fct_collapse(LIENPREF, "pere-mere" = c("1", "2"))) %>%
  mutate(LIENPREF = fct_other(LIENPREF, keep = "pere-mere")) %>%
  group_by(LIENPREF) %>%
  count

PCS56_LIENPREF <- individus %>%
  filter(CS24L == 56) %>%
  mutate(LIENPREF = fct_collapse(LIENPREF, "pere-mere" = c("1", "2"))) %>%
  mutate(LIENPREF = fct_other(LIENPREF, keep = "pere-mere")) %>%
  group_by(LIENPREF) %>%
  count

lienpref <- ALL_LIENPREF %>% full_join(PCS56_LIENPREF, by = c("LIENPREF"), suffix = c(" all", " pcs_56"))
```
```{r, echo=FALSE}
knitr::kable(lienpref, caption = "Lien à la personne de référence")
```

## Modèle logistique

### Préparation

```{r}
library(survey)
library(gtsummary)
library(forestmodel)

prepare_individus_for_regression <- function (data) {
  data <- data %>%
    # Variable "is_PCS56"
    mutate(is_PCS56 = (CS24L == 56) & (!is.na(CS24L))) %>%
    # Adapation des sexes
    mutate(SEXE = fct_recode(SEXE, "Homme" = "1", "Femme" = "2")) %>%
    # 15 ans et plus, adapatation des tranches d'âge
    filter(AGE >= 15) %>%
    mutate(TRAGE = fct_drop(TRAGE)) %>%
    mutate(TRAGE = fct_recode(TRAGE, "[15;24]" = "2", "[25;34]" = "3", "[35;44]" = "4", "[45;54]" = "5", "[55;64]" = "6", "[65;74]" = "7")) %>%
    # Simplification des niveaux de diplôme et modalité de référence = bac
    mutate(DIPL = fct_explicit_na(DIPL)) %>%
    mutate(DIPL = fct_collapse(DIPL, "En cours" = c("1", "8"), "Inf. au lycée" = c("0", "2", "3"), "Lycée" = c("4"), "Bac" = c("5"), "Sup. au bac" = c("6", "7", "9"))) %>%
    mutate(DIPL = fct_relevel(DIPL, "Bac")) %>%
    # Adapation des lieux de travail
    mutate(TYPLT = fct_explicit_na(TYPLT)) %>%
    mutate(TYPLT = fct_recode(TYPLT, "Bureau" = "1", "Commerce, boutique, grandes surfaces" = "2", "Entrepôt, usine, atelier" = "3", "Universités, collèges, lycées" = "4", "Hôpital" = "5", "Aéroports / gares" = "6", "Chez des particuliers" = "7", "Zones spéciales (Rungis, portuaires)" = "8", "Domicile" = "9", "Autres" = "10")) %>%
    # Adapation de la variabilité des lieux de travail
    mutate(ULTRAV = fct_explicit_na(ULTRAV)) %>%
    mutate(ULTRAV = fct_recode(ULTRAV, "Unique, en dehors du domicile" = "1", "Unique, au domicile" = "2", "Pas de lieu fixe" = "3")) %>%
    # Adaptation de la localisation du lieu de travail
    mutate(LTRAVCOUR = fct_explicit_na(LTRAVCOUR)) %>%
    mutate(LTRAVCOUR = fct_recode(LTRAVCOUR, "Paris" = "1", "Petite couronne" = "2", "Grande Couronne" = "3")) %>%
    # Adapatation du permis de conduire
    # mutate(PERMVP = fct_explicit_na(PERMVP)) %>% # Commenté car que 1 personne et ça complique la lecture
    mutate(PERMVP = fct_recode(PERMVP, "Oui" = "1", "Non" = "2", "Conduite accompagnée ou leçons" = "3")) %>%
    # Adaptation de l'abonnement TC
    mutate(ABONTC = fct_explicit_na(ABONTC)) %>%
    mutate(ABONTC = fct_other(ABONTC, keep = "1", other_level = "Oui")) %>%
    mutate(ABONTC = fct_recode(ABONTC, "Non" = "1")) %>%
    # Modalité de référence pour la gêne dans les déplacements = oui
    mutate(HANDI = fct_explicit_na(HANDI)) %>%
    mutate(HANDI = fct_relevel(HANDI, "2")) %>%
    mutate(HANDI = fct_recode(HANDI, "Oui" = "1", "Non" = "2"))
  data
}

individus_for_regression <- prepare_individus_for_regression(individus)
  
individus_pere_mere_for_regression <- individus_for_regression %>%
  # On ne garde que les pères et mères
  mutate(LIENPREF = fct_collapse(LIENPREF, "pere-mere" = c("1", "2"))) %>%
  mutate(LIENPREF = fct_other(LIENPREF, keep = "pere-mere")) %>%
  filter(LIENPREF == "pere-mere")
```

### Régression
```{r}
weighted_individus_pere_mere_for_regression <- svydesign(ids = ~1,
  data = individus_pere_mere_for_regression, weights = ~POIDSP)

reg_pere_mere <- svyglm(is_PCS56 ~ SEXE + TRAGE + DIPL + TYPLT + ULTRAV + LTRAVCOUR + PERMVP + ABONTC + HANDI,
  weighted_individus_pere_mere_for_regression, family = quasibinomial())

weighted_individus_for_regression <- svydesign(ids = ~1,
  data = individus_for_regression, weights = ~POIDSP)

reg <- svyglm(is_PCS56 ~ SEXE + TRAGE + DIPL + TYPLT + ULTRAV + LTRAVCOUR + PERMVP + ABONTC + HANDI,
  weighted_individus_for_regression, family = quasibinomial())

```

### Tous les individus
```{r}
tbl_regression(reg, exponentiate = TRUE)
```
```{r}
forest_model(reg)
```

### Que les pères et mères

```{r}
tbl_regression(reg_pere_mere, exponentiate = TRUE)
```
```{r}
forest_model(reg_pere_mere)
```

